// Reference material PDFs served by the backend at /materials/<filename>
// URL: `${import.meta.env.VITE_API_URL}/materials/${encodeURIComponent(file)}`

export const MATERIAL_GROUPS = [
  {
    id: "q1-risk",
    label: "Risk Analysis & Security Processes (Q1)",
    color: "blue",
    items: [
      { file: "Equifax-Report.pdf",                    title: "Equifax Breach Post-Mortem",              note: "Patch management failure — Apache Struts CVE; canonical Q1 case study" },
      { file: "spafford88internet.pdf",                title: "Spafford 1988 — Morris Worm",             note: "Foundational incident; asked directly in nds106-2003 Q1" },
      { file: "stuxnet-Cyber-Reports-2017-04.pdf",     title: "Stuxnet Report (2017)",                  note: "Supply-chain / ICS targeting" },
      { file: "w32_stuxnet_dossier.pdf",               title: "Stuxnet Dossier (Symantec)",              note: "Technical deep-dive companion to the report" },
      { file: "mirai-7132482937526820422.pdf",         title: "Mirai Botnet Analysis",                  note: "Default-credential IoT disaster; DoS via botnets" },
      { file: "Eurograbber_White_Paper.pdf",           title: "Eurograbber Whitepaper",                 note: "Mobile-banking Zeus variant; good Q1 risk-analysis anecdote" },
      { file: "BlueBorne Technical White Paper.pdf",   title: "BlueBorne (Bluetooth RCE)",              note: "OS/runtime patching as process issue" },
      { file: "stagefright.pdf",                       title: "Stagefright (Android MMS RCE)",          note: "Patching velocity as risk" },
      { file: "2013-java-0day.pdf",                    title: "Java 0-Day 2013",                        note: "Patch management failure" },
      { file: "pci_dss_v3-2.pdf",                      title: "PCI-DSS v3.2",                           note: "Compliance-driven process example" },
      { file: "attack-surface-1-s2.0-S0950584918301514-main.pdf", title: "Attack Surface Survey",      note: "Formalises the attack-surface concept" },
      { file: "rapid7-survey.pdf",                     title: "Rapid7 Threat Survey",                   note: "Attack statistics / risk prioritisation" },
      { file: "wp-caught-in-the-act-running-a-realistic-factory-honeypot-to-capture-real-threats.pdf", title: "ICS Honeypot — Caught in the Act", note: "ICS targeting evidence" },
      { file: "wp-whos-really-attacking-your-ics-equipment.pdf", title: "Who's Really Attacking Your ICS?", note: "ICS attacker profiles" },
      { file: "WhyFromNigeria.pdf",                    title: "Why From Nigeria? (Spam / Social Engineering)", note: "Phishing / social engineering background" },
      { file: "Greenbone_Security_Report_Unprotected_Patient_Data_a_Review.pdf", title: "Greenbone — Unprotected Patient Data", note: "Healthcare GDPR exposure" },
      { file: "linux-root-vuln.pdf",                   title: "Linux Root Vulnerability Case Study",    note: "Privilege escalation process risk" },
      { file: "2020-01-14-out-of-control-final-version.pdf", title: "Out of Control (sudo vuln 2020)", note: "sudo privilege escalation" },
      { file: "intel-csme-security-white-paper.pdf",   title: "Intel CSME Security",                   note: "Firmware/supply-chain risk" },
      { file: "1780_27c3_console_hacking_2010.pdf",    title: "Console Hacking 2010 (27C3)",            note: "Hardware / process security" },
      { file: "fake-twitter-russians-17.001.02.pdf",   title: "Fake Twitter — Russian Influence Ops",  note: "Disinformation as risk in Q1 election scenarios" },
      { file: "ai-oops-2508.06394v1.pdf",              title: "AI Security Oops (2025)",               note: "AI/LLM security failures — relevant to Q1 2026" },
    ],
  },
  {
    id: "crypto",
    label: "Cryptography (Q2 sub-parts)",
    color: "emerald",
    items: [
      { file: "simplified-DES.pdf",               title: "Simplified DES",                  note: "Minimal example for block cipher structure" },
      { file: "des-870612.pdf",                   title: "DES 1987 Paper",                  note: "Historical cipher design" },
      { file: "gcm.pdf",                          title: "GCM (AEAD) Paper",                note: "AES-GCM reference — why AEAD is correct" },
      { file: "AE_comparison_ipics04.pdf",        title: "AE Modes Comparison (2004)",      note: "MAC-then-encrypt vs encrypt-then-MAC" },
      { file: "shattered.pdf",                    title: "SHAttered — SHA-1 Collision",     note: "First identical-prefix SHA-1 collision 2017" },
      { file: "shattered-1.pdf",                  title: "SHAttered File 1",                note: "Identical-prefix collision example" },
      { file: "shattered-2.pdf",                  title: "SHAttered File 2",                note: "Identical-prefix collision example" },
      { file: "SHA-1_Collision.pdf",              title: "SHA-1 Collision Analysis",        note: "Related collision research" },
      { file: "2020-014.pdf",                     title: "SHA-1 is a Shambles (2020)",      note: "Chosen-prefix SHA-1 collision — Flame/MD5 pattern repeats" },
      { file: "flame-md5.pdf",                    title: "Flame Malware — MD5 Collision",  note: "Real-world MD5 collision weaponised for CA spoofing" },
      { file: "rsa-768-broken.pdf",               title: "RSA-768 Factored",               note: "Why 2048-bit RSA minimum" },
      { file: "lenstra-common-factors.064.pdf",   title: "Lenstra — Common Factors in RSA Keys", note: "Weak key generation in embedded devices" },
      { file: "rsa-crt-leaks.pdf",                title: "RSA-CRT Leaks",                  note: "Side-channel from CRT optimisation" },
      { file: "rsa-acoustic-857.pdf",             title: "RSA Acoustic Attacks",           note: "Acoustic side-channel on RSA" },
      { file: "lightweight-crypto-survey.pdf",    title: "Lightweight Crypto Survey",       note: "IoT / embedded crypto choices" },
      { file: "SimonSpeckPerformance1.pdf",       title: "Simon/Speck Performance",         note: "NSA lightweight ciphers debate" },
      { file: "djb.pdf",                          title: "DJB — Curve25519",               note: "X25519 / EdDSA rationale" },
      { file: "gost-178-bit-attack-138.pdf",      title: "GOST 178-bit Attack",            note: "Alternate cipher failure" },
      { file: "Kocher2011_Article_IntroductionToDifferentialPowe.pdf", title: "Kocher — Introduction to DPA", note: "Power analysis side-channel foundational paper" },
    ],
  },
  {
    id: "tls-protocols",
    label: "TLS & Protocols (Q2 core)",
    color: "purple",
    items: [
      { file: "tls13-awacs.pdf",                  title: "TLS 1.3 AWACS Analysis",         note: "Deep analysis of TLS 1.3 design" },
      { file: "Armis-TLStorm.pdf",                title: "Armis TLStorm (2022)",           note: "APC UPS TLS parser bugs; good named attack" },
      { file: "imperfect-forward-secrecy-ccs15.pdf", title: "Logjam / Imperfect Forward Secrecy", note: "Export-grade DH downgrade attack" },
      { file: "bleichenbacher-pkcs.pdf",          title: "Bleichenbacher PKCS#1 v1.5",     note: "Original padding oracle; ancestor of ROBOT" },
      { file: "robot-1189.pdf",                   title: "ROBOT Attack (2017)",            note: "Bleichenbacher returns in F5/Citrix" },
      { file: "Drown_Attack.pdf",                 title: "DROWN Attack",                   note: "SSLv2 cross-protocol oracle" },
      { file: "drown-attack-paper.pdf",           title: "DROWN Full Paper",               note: "Extended DROWN analysis" },
      { file: "TLStiming.pdf",                    title: "TLS Timing Attacks",             note: "Lucky13 / CBC timing side-channel" },
      { file: "DualECTLS.pdf",                    title: "Dual-EC in TLS",                 note: "Backdoored PRNG in Juniper" },
      { file: "slides-99-irtfopen-anrp-stephen-checkoway-a-systematic-analysis-of-the-juniper-dual-ec-incident-00.pdf", title: "Juniper Dual-EC Incident (IRTF)", note: "Systematic analysis of NSA backdoor" },
      { file: "tls-mitm-boxes.pdf",               title: "TLS MITM Boxes",                 note: "Corporate SSL inspection breaking security" },
      { file: "interception-ndss17.pdf",          title: "TLS Interception (NDSS 2017)",   note: "Measuring corporate MITM in the wild" },
      { file: "tls-malware-without-decryption.pdf", title: "TLS Malware Detection (no decryption)", note: "Traffic analysis approach" },
      { file: "non-browser-ssl-shmat_ccs12.pdf",  title: "Non-Browser SSL is Broken",      note: "Accept-all-certs in apps" },
      { file: "p50-fahl.pdf",                     title: "Fahl — Dev-Side TLS Misuse",     note: "Why developers break TLS validation" },
      { file: "ssl-mitm-dell-secureworks-article.pdf", title: "Dell Secureworks SSL MITM", note: "Certificate interception in practice" },
      { file: "ssl_jun21.pdf",                    title: "SSL June 2021",                  note: "TLS ecosystem snapshot" },
      { file: "crlite_oakland17.pdf",             title: "CRLite — Web PKI Revocation at Scale", note: "Bloom-filter based revocation" },
      { file: "dtls.pdf",                         title: "DTLS Paper",                     note: "TLS over UDP for real-time" },
      { file: "google_infrastructure_whitepaper_fa.pdf", title: "Google Infrastructure Whitepaper", note: "ALTS / large-scale authenticated transport" },
      { file: "slides-85-saag-1.pdf",             title: "SAAG Slides",                    note: "IETF security area context" },
    ],
  },
  {
    id: "dns-dnssec",
    label: "DNS & DNSSEC (Q4)",
    color: "cyan",
    items: [
      { file: "June3_DNSSEC.pdf",                        title: "June3 DNSSEC Lecture",     note: "Primary reference — lecture-style comprehensive overview" },
      { file: "dnspolicy-10.1002@poi3.195.pdf",          title: "DNS Policy (ICANN)",       note: "Governance and policy context" },
      { file: "dontlookup_ccs25_fullpaper.pdf",          title: "Don't Look Up (CCS 2025)", note: "Recent DNS attack research; add colour to Q4 answers" },
    ],
  },
  {
    id: "pqc-hpke",
    label: "PQC / HPKE / E2EE (Q2 sub-parts)",
    color: "indigo",
    items: [
      { file: "2001.07421.pdf",           title: "PQC Survey / Transition Context",       note: "Overview of post-quantum migration" },
      { file: "2204.10920.pdf",           title: "PQC in TLS / Migration",                note: "Hybrid KEM in TLS" },
      { file: "mls-study.pdf",            title: "MLS (Messaging Layer Security)",        note: "HPKE as building block for group messaging" },
      { file: "e2ee-2022-449.pdf",        title: "E2EE Design 2022",                      note: "Encrypted-at-rest / E2EE architecture" },
      { file: "WhatsAppEncryption.pdf",   title: "WhatsApp Encryption",                   note: "Signal / Double-Ratchet in practice" },
      { file: "endtoend.pdf",             title: "End-to-End Encryption Analysis",        note: "E2EE properties and limitations" },
      { file: "coniks-1004.pdf",          title: "CONIKS — Key Transparency",             note: "Auditable key directories" },
    ],
  },
  {
    id: "passwords",
    label: "Passwords & Authentication (Q1/Q3 sub-parts)",
    color: "yellow",
    items: [
      { file: "2012-jbonneau-phd_thesis.pdf",          title: "Bonneau PhD Thesis — Passwords (2012)", note: "Statistics and entropy framing for password security" },
      { file: "Oech03.pdf",                             title: "Oechslin 2003 — Rainbow Tables",        note: "Time-memory tradeoff; origin of rainbow tables" },
      { file: "WP_Consumer_Password_Worst_Practices.pdf", title: "Consumer Password Worst Practices", note: "Easy anecdotes for Q1 auth risks" },
      { file: "johnny-fired.pdf",                       title: "Why Johnny Was Fired (Usability)",      note: "Usability / auth failure classic" },
    ],
  },
  {
    id: "privacy-legal",
    label: "Privacy, Legal & Censorship (Q1/Q3/Q4 sub-parts)",
    color: "rose",
    items: [
      { file: "us-ftc-140527databrokerreport.pdf",      title: "FTC Data Broker Report (2014)",          note: "Data broker practices and privacy harms" },
      { file: "us-ws-on-accesstoplain-23593.pdf",       title: "Workshop on Access to Plaintext",        note: "Lawful-access / backdoor debate" },
      { file: "read-the-nsc-draft-options-paper-on-strategic.pdf", title: "NSC Options Paper (Strategic)", note: "US policy on crypto / lawful access" },
      { file: "CRISIS-1996-crypto-report-5131.pdf",     title: "CRISIS 1996 Crypto Policy Report",       note: "Historical crypto export control context" },
      { file: "SSRN-id2911978.pdf",                     title: "SSRN Law/Tech Paper",                    note: "Legal/technical intersection" },
      { file: "india-censorship-1912.08590.pdf",        title: "India Censorship Study (2019)",          note: "DNS poisoning / SNI blocking at scale" },
      { file: "outages_censorship.pdf",                 title: "Internet Outages & Censorship",          note: "BGP hijack / shutdown measurement" },
      { file: "privacyscore.org-1705.05139.pdf",        title: "PrivacyScore",                           note: "Website privacy scoring methodology" },
      { file: "trackers.1712.06850.pdf",                title: "Web Trackers Analysis",                  note: "Third-party tracking at scale" },
      { file: "The Perpetual Line-Up - Center on Privacy and Technology at Georgetown Law.pdf", title: "The Perpetual Line-Up (Georgetown)", note: "Facial recognition + privacy policy" },
      { file: "robust-website-fingerprinting.pdf",      title: "Robust Website Fingerprinting",          note: "Traffic analysis for censorship circumvention" },
      { file: "ji-poltergeist-oakland21.pdf",           title: "Poltergeist (Oakland 2021)",             note: "Adversarial attacks on AI sensors" },
      { file: "2020-01-14-out-of-control-final-version.pdf", title: "Out of Control — IoT Tracking",    note: "Mobile app data leakage" },
    ],
  },
  {
    id: "side-channels",
    label: "Side-Channels & Hardware Attacks (Q2 sub-parts)",
    color: "orange",
    items: [
      { file: "meltdown.pdf",                    title: "Meltdown (2018)",               note: "Speculative execution — kernel memory leak" },
      { file: "spectre.pdf",                     title: "Spectre (2018)",                note: "Branch prediction side-channel" },
      { file: "acoustic-leak.pdf",               title: "Acoustic Cryptanalysis",        note: "RSA key extraction via acoustic emissions" },
      { file: "synesthesia.pdf",                 title: "Synesthesia — Screen Eavesdropping", note: "EM side-channel from display" },
      { file: "ccs18_camurati_preprint.pdf",     title: "Screaming Channels (CCS 2018)", note: "RF side-channel from mixed-signal chips" },
      { file: "handsoff-20140731.pdf",           title: "Hands Off My Laptop",          note: "Side-channel via USB/power" },
      { file: "jscacheattack.pdf",               title: "JavaScript Cache Timing Attack", note: "Browser-based side-channel" },
      { file: "page-cache-1901.01161.pdf",       title: "Page Cache Attacks",            note: "OS page cache as information leak" },
      { file: "nethammer-1805.04956.pdf",        title: "NetHammer — Rowhammer over Network", note: "Rowhammer via network traffic" },
      { file: "moar-rowhammer.pdf",              title: "More Rowhammer",               note: "DRAM bit-flip exploitation" },
      { file: "20240903_eucleak.pdf",            title: "EuCleak (2024)",               note: "Side-channel on YubiKey (ECDSA nonce)" },
      { file: "anc_ndss17.pdf",                  title: "ASLR Cache (NDSS 2017)",       note: "Cache-based ASLR bypass" },
      { file: "moredhe-999.pdf",                 title: "MoreDHE",                      note: "DH timing attacks" },
    ],
  },
  {
    id: "iot-embedded",
    label: "IoT, Embedded & Telecom",
    color: "teal",
    items: [
      { file: "cars-usenixsec2011.pdf",          title: "Comprehensive Car Hacking (USENIX 2011)", note: "CAN bus attacks on vehicles" },
      { file: "p468-checkoway.pdf",              title: "Checkoway — Car Attack (Remote)", note: "Remote vehicle compromise" },
      { file: "bh-eu-13-floating-car-data-jeske-wp.pdf", title: "Floating Car Data Privacy", note: "Vehicle tracking and privacy" },
      { file: "iot-crap-1708.05044.pdf",         title: "IoT Security is a Mess",        note: "Survey of IoT vulnerabilities" },
      { file: "viehboeck_wps.pdf",               title: "Viehböck — WPS PIN Brute-Force", note: "WPA2-WPS design flaw" },
      { file: "Nov28_GPS.pdf",                   title: "GPS Spoofing",                  note: "Navigation system attacks" },
      { file: "SSTIC2017-Article-remote_geolocation_and_tracing_of_subscribers_using_4g_volte_android_phone-le-moal_ventuzelo_coudray.pdf", title: "4G/VoLTE Geolocation Tracking (SSTIC 2017)", note: "Subscriber tracking via IMS" },
    ],
  },
  {
    id: "web-infra",
    label: "Web, Infrastructure & Misc",
    color: "gray",
    items: [
      { file: "websso-final.pdf",                title: "Web SSO Security Analysis",      note: "OAuth/SSO vulnerability patterns" },
      { file: "Nikiforakis.pdf",                 title: "Nikiforakis — Web Tracking",     note: "Browser fingerprinting and tracking" },
      { file: "CCS15.pdf",                       title: "CCS 2015 Paper",                 note: "Web security research" },
      { file: "bitcoin.pdf",                     title: "Bitcoin Whitepaper (Nakamoto)",  note: "Blockchain / distributed consensus" },
      { file: "bitcoinprotocol.pdf",             title: "Bitcoin Protocol Analysis",      note: "Protocol-level security analysis" },
      { file: "efail-attack-paper.pdf",          title: "EFAIL (PGP/S-MIME oracle)",      note: "Email E2EE vulnerability" },
      { file: "raluca-cryptdb.pdf",              title: "CryptDB — Encrypted Databases",  note: "Query over encrypted data" },
      { file: "patch-1712.09665.pdf",            title: "Patch Deployment Analysis",      note: "How fast do patches get applied?" },
      { file: "foolbox-1712.04248.pdf",          title: "Foolbox — Adversarial ML",      note: "Adversarial examples / AI robustness" },
      { file: "kohnfelder-07113748-MIT.pdf",     title: "Kohnfelder 1978 — PKI Certificates", note: "Origin of the public key certificate concept" },
      { file: "nsa-buying-fe33e1ba-full.pdf",    title: "NSA Buying Capabilities",       note: "Offensive capability procurement" },
      { file: "popets-2021-0042.pdf",            title: "PoPETs 2021 Privacy Paper",     note: "Privacy enhancing technologies" },
      { file: "The_Bvp47_a_top-tier_backdoor_of_us_nsa_equation_group.en.pdf", title: "BVP47 — NSA Equation Group Backdoor", note: "Nation-state implant analysis" },
      { file: "2204.10920.pdf",                  title: "PQC in TLS",                    note: "Hybrid PQC key exchange" },
      { file: "SSRN-id2911978.pdf",              title: "SSRN Tech/Law",                 note: "Regulatory / compliance reading" },
    ],
  },
]
